# Generated by Django 4.1.5 on 2023-01-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_messages_options_alter_messages_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
