# Generated by Django 4.1.5 on 2023-01-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_messages_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
